In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score as ac
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier

In [30]:
c_data=pd.read_csv("Company_Data (1).csv")
c_data.head(2)

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes

In [31]:
lm=LabelEncoder()
c_data["Urban"]=lm.fit_transform(c_data["Urban"])
c_data["US"]=lm.fit_transform(c_data["US"])
c_data["ShelveLoc"]=lm.fit_transform(c_data["ShelveLoc"])

In [32]:
c_data.head(3)

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   

   Education  Urban  US  
0         17      1   1  
1         10      1   1  
2         12      1   1

In [33]:
X=c_data.iloc[:,1:]
Y=c_data.iloc[:,0]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=10)

In [36]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

LETS USE THE RANDOM FOREST REGRESSOR SINCE THE TARGET VARIABLE IS CATERGORICAL 

In [37]:
model=RandomForestRegressor()

In [38]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [39]:
y_pred=model.predict(x_test)

In [40]:
model.score(x_test,y_test)

0.6395835960745548

In [41]:
model.feature_importances_

array([0.08583273, 0.05478473, 0.08136832, 0.04088122, 0.30500247,
       0.30353086, 0.08535925, 0.03308539, 0.00575816, 0.00439688])

In [42]:
y_pred

array([ 6.9036,  6.639 , 10.2693,  4.9359,  9.8115,  5.817 ,  6.6776,
        6.8584,  7.059 ,  8.1448,  6.4152, 10.8514,  7.2064,  8.6697,
        7.505 ,  6.455 ,  4.4128,  4.7449,  5.8642,  8.6007,  5.3034,
        8.2821,  8.7067,  4.4871,  6.3786,  5.4603,  9.6951,  6.2952,
        6.8665,  5.9087, 11.913 ,  6.6527,  7.4298,  8.6911,  7.3941,
        5.7571, 11.551 ,  8.3169,  8.4185,  8.7493, 10.7744,  5.3594,
        8.9514,  7.1956,  5.4191,  7.1627,  8.5807,  8.5033,  7.9526,
        4.3727,  6.0644,  7.557 ,  4.3767, 10.1284,  6.5256, 12.0687,
        6.7347,  7.182 ,  6.9032, 10.6105,  6.3849,  4.7037,  5.956 ,
        6.4581,  3.8569,  8.2994,  9.1049,  8.2743,  7.3385,  8.1496,
        8.9196,  5.5259,  5.0809,  7.8471,  5.0676,  9.5935,  4.5193,
        6.397 ,  8.9154,  6.4513,  9.343 ,  9.7521,  9.9757,  7.3179,
        8.0178,  6.7591,  7.7009,  7.8165,  8.115 ,  8.0166,  6.6457,
        7.975 ,  5.4115, 10.2503,  5.3827,  9.8919,  7.0539,  5.0405,
        8.0596,  8.6

In [43]:
from sklearn import metrics

In [52]:
metrics.mean_squared_error(y_test,y_pred)
print("mean_squared_error:",metrics.mean_squared_error(y_test,y_pred))

mean_squared_error: 2.476152344242422


In [53]:
metrics.mean_absolute_error(y_test,y_pred)
print("mean_absolute_error:",metrics.mean_absolute_error(y_test,y_pred))

mean_absolute_error: 1.2603757575757573


In [54]:
metrics.mean_absolute_percentage_error(y_test,y_pred)
print("mean_absolute_percentage_error:",metrics.mean_absolute_percentage_error(y_test,y_pred))

mean_absolute_percentage_error: 0.20389903769379195


In [56]:
print("root mean_squared_error:",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

root mean_squared_error: 1.5735794686772009


# lets do bagging and boosting

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score,KFold
from sklearn.ensemble import BaggingClassifier,BaggingRegressor,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

In [2]:
c_d=pd.read_csv("Company_Data (1).csv")
c_d.head(3)

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes

In [3]:
# using label encoder for the categorical values
from sklearn.preprocessing import LabelEncoder
lm=LabelEncoder()
c_d['ShelveLoc']=lm.fit_transform(c_d['ShelveLoc'])
c_d['Urban']=lm.fit_transform(c_d['Urban'])
c_d['US']=lm.fit_transform(c_d['US'])

In [4]:
c_d.head(3)

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   

   Education  Urban  US  
0         17      1   1  
1         10      1   1  
2         12      1   1

In [9]:
# standraize the vlues
def n_funtion (i):
    x=(i-i.min()/i.max()-i.min())
    return(x)


In [12]:
c_d1=n_funtion(c_d)
c_d1.head(3)

Sales  CompPrice  Income  Advertising  Population      Price  ShelveLoc  \
0   9.50      60.56  51.825         11.0  265.980354  95.874346        0.0   
1  11.22      33.56  26.825         16.0  249.980354  58.874346        1.0   
2  10.06      35.56  13.825         10.0  258.980354  55.874346        2.0   

       Age  Education  Urban   US  
0  16.6875   6.444444    1.0  1.0  
1  39.6875  -0.555556    1.0  1.0  
2  33.6875   1.444444    1.0  1.0

In [13]:
# usse bagging
x=c_d1.iloc[:,1:]
y=c_d1.iloc[:,0]

In [14]:
model=BaggingRegressor()
model.fit(x,y)

BaggingRegressor()

In [15]:
y_pred=model.predict(x)
y_pred

array([ 8.325, 10.922,  9.158,  7.955,  4.345, 10.543,  6.284, 11.198,
        6.174,  5.213,  6.748, 11.517,  3.759, 11.487, 10.343,  7.236,
        7.779, 11.754, 12.605,  8.268,  5.962, 11.335,  5.17 ,  5.623,
        8.379, 13.781,  8.729,  6.378,  3.294,  6.973, 13.351,  7.832,
        7.334,  9.23 ,  3.537, 10.369,  9.441,  4.904,  6.494,  3.578,
        2.439,  7.609, 10.541,  4.745,  6.911,  4.085, 12.16 ,  4.741,
        4.72 ,  9.721,  3.535,  4.431,  7.683,  6.59 ,  5.103,  6.316,
       10.484,  1.995,  5.223,  5.416,  7.347,  6.79 ,  3.279,  8.214,
        7.968,  4.717,  8.925,  8.956, 12.659,  7.949,  9.601,  6.884,
        6.825, 11.139,  7.308,  9.138, 10.433,  8.381,  4.416,  8.071,
        8.216,  7.82 ,  9.835,  5.73 ,  2.657,  7.892,  7.778, 11.356,
        6.565,  7.728,  5.638,  4.482,  6.08 ,  8.556,  8.237,  5.361,
        9.299,  7.366, 11.584,  4.837,  4.924,  6.9  ,  5.526,  6.399,
        5.272,  6.431,  1.758,  8.315,  3.502,  8.35 ,  8.379,  6.394,
      

In [17]:
model.feature_names_in_

array(['CompPrice', 'Income', 'Advertising', 'Population', 'Price',
       'ShelveLoc', 'Age', 'Education', 'Urban', 'US'], dtype=object)

In [19]:
from sklearn import metrics

In [20]:
metrics.mean_squared_error(y,y_pred)
print("mean_sq_err",metrics.mean_squared_error(y,y_pred))

mean_sq_err 0.50939297


In [22]:
metrics.mean_absolute_error(y,y_pred)
print("mean_absolute_error:",metrics.mean_absolute_error(y,y_pred))

mean_absolute_error: 0.5375749999999999


In [26]:
metrics.mean_absolute_percentage_error(y,y_pred)
print("mean_absolute_percentage_error:",metrics.mean_absolute_percentage_error(y,y_pred))

mean_absolute_percentage_error: 29048217596539.82


In [27]:
#using train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [29]:
model1=BaggingRegressor()
model1.fit(x_train,y_train)

BaggingRegressor()

In [30]:
y_pred=model1.predict(x_test)
y_pred

array([ 7.575,  6.026,  9.317,  5.258, 10.94 ,  6.758,  6.613,  7.278,
        7.844,  7.371,  7.157, 10.137,  6.578,  8.009,  8.02 ,  8.316,
        4.199,  5.654,  6.225,  9.867,  5.164,  8.593,  9.461,  4.593,
        6.062,  5.589,  9.344,  6.762,  6.171,  5.547, 10.557,  6.627,
        7.576,  9.358,  8.376,  7.264, 11.618,  6.993,  8.535,  8.653,
        9.76 ,  5.107, 10.371,  7.032,  7.209,  7.33 ,  8.155,  8.058,
        7.215,  4.734,  5.631,  7.746,  5.332, 10.202,  6.669, 12.602,
        7.445,  6.488,  4.611,  9.65 ,  6.316,  4.912,  6.059,  5.714,
        4.517,  8.45 ,  9.168,  7.509,  6.414,  8.562,  7.95 ,  5.491,
        6.22 ,  7.84 ,  4.52 , 10.401,  4.294,  6.769,  7.766,  7.037])

In [31]:
metrics.mean_squared_error(y_test,y_pred)
print("mean_sq_err",metrics.mean_squared_error(y_test,y_pred))

mean_sq_err 2.4469763125


In [32]:
metrics.mean_absolute_error(y_test,y_pred)
print("mean_absolute_error:",metrics.mean_absolute_error(y_test,y_pred))

mean_absolute_error: 1.2612374999999998


In [33]:
from sklearn.ensemble import AdaBoostRegressor
model3=AdaBoostRegressor()
model3.fit(x_train,y_train)


AdaBoostRegressor()

In [34]:
y_pr=model3.predict(x_test)
y_pr

array([ 8.38938776,  7.95477273, 10.07764706,  6.05095745, 10.27      ,
        6.74111111,  5.23366667,  6.42852941,  6.83125   ,  7.76115942,
        7.27083333,  9.90032   ,  6.40243478,  9.16983051,  8.61571429,
        7.67276923,  5.3762    ,  5.73693548,  7.76115942,  9.27387324,
        6.34153846,  8.16477941,  9.24852713,  5.06836364,  7.76115942,
        5.93552147,  9.48884058,  7.55605505,  6.64478992,  6.34153846,
       10.58009615,  5.79710744,  7.11724138,  9.61340909,  8.49438596,
        7.11724138, 11.3985    ,  8.07328571,  9.24604167,  9.27387324,
        7.77733333,  6.00612245,  9.16983051,  7.45083333,  5.79710744,
        7.105     ,  8.07328571,  7.55790323,  7.55605505,  5.94065934,
        7.20214286,  6.89721649,  5.00185185,  9.90032   ,  6.40243478,
       11.1512    ,  6.05095745,  6.68      ,  5.94065934,  9.81382979,
        6.47591398,  5.43066667,  5.93552147,  6.47591398,  5.16394366,
        7.67276923,  9.65397849,  8.38938776,  6.01693182,  8.72

In [35]:
metrics.mean_absolute_error(y_test,y_pr)
print("mean_absolute_error:",metrics.mean_absolute_error(y_test,y_pr))

mean_absolute_error: 1.3164151381940539
